version: "3"
services:
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8090:8080"
    volumes: 
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices: 
      - "/dev/kmsg"
    networks:
      - monitoring

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes: 
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - monitoring
    depends_on:
      - cadvisor

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - DS_PROMETHEUS=prometheus
    volumes: 
      - grafana-data:/var/lib/grafana
      - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:rw
      - ./dashboard.json:/var/lib/grafana/dashboards/dashboard.json:rw
      - ./default.yaml:/etc/grafana/provisioning/dashboards/default.yaml:rw
    privileged: true
    networks:
      - monitoring
    depends_on:
      - prometheus
  
  tunnel:
    depends_on:
      - grafana  # Depends on grafana service
    # Cloudflared Tunnel is used to securely connect to Cloudflare's network.
    container_name: grafana-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run --token "$CLOUDFLARE_TOKEN"
    env_file:
      - .env  # Environment variables
    networks:
      - monitoring

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    networks: 
      - monitoring
volumes:
  grafana-data:

networks:
  monitoring:
