version: "3.8"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    ports:
      # DNS Ports (LAN only)
      - "53:53/tcp"
      - "53:53/udp"
      # HTTP Web UI
      - "80:80/tcp"
      # HTTPS Web UI with self-signed cert
      - "443:443/tcp"
      # Optional: DHCP (if you want Pi-hole to act as DHCP server)
      # - "67:67/udp"

    environment:
      # Timezone
      TZ: 'America/Los_Angeles'
      # Web interface password (change this!)
      FTLCONF_webserver_api_password: 'correct horse battery staple'
      # Query log retention (7 days)
      FTLCONF_MAXDBDAYS: 7

    volumes:
      # Persistent data storage
      - ./etc-pihole:/etc/pihole
      # Optional: for custom dnsmasq configs
      # - ./etc-dnsmasq.d:/etc/dnsmasq.d

    cap_add:
      - NET_ADMIN  # Needed for DHCP, safe to leave

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "dig", "@127.0.0.1", "pi.hole"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
