version: '3'

services:
  adguardhome:
    image: adguard/adguardhome
    ports:
      - "53:53/tcp" # plain dns over tcp
      - "53:53/udp" # plain dns over udp
      - "80:80/tcp" # http web interface
      - "9001:3000/tcp" # initial setup web interface
    volumes:
      - ./config:/opt/adguardhome/conf:rw # app configuration
      - ./work:/opt/adguardhome/work:rw # app working directory

volumes:
  config:
    driver: local
  work:
    driver: local