---
- name: Install SSH services and copy host keys to client
  hosts: client
  become: yes
  vars_files:
    - .env

  tasks:
    - name: Install SSH service on Debian
      apt:
        name: openssh-server
        state: present

    - name: Start and enable SSH service
      service:
        name: ssh
        state: started
        enabled: yes

    - name: Copy SSH public key to client
      copy:
        src: ~/.ssh/id_ed25519.pub
        dest: /tmp/id_ed25519.pub
      delegate_to: localhost

    - name: Append SSH public key to authorized_keys on client
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '/tmp/id_ed25519.pub') }}"

    - name: Set hostname
      hostname:
        name: "Miles_Cube_Node_1"

    - name: Configure static IP
      lineinfile:
        path: /etc/network/interfaces
        regexp: '^address'
        line: "address 192.168.0.201"
        state: present
      notify: Restart networking

    - name: Create k3s config directory
      file:
        path: /etc/rancher/k3s
        state: directory
        mode: '0755'

    - name: Create k3s config file
      copy:
        dest: /etc/rancher/k3s/config.yaml
        content: |
          disable:
           - traefik # Disable the default Traefik ingress controller

          secrets-encryption: true # Enable secrets encryption

          write-kubeconfig-mode: "0644" # Set kubeconfig file mode
          write-kubeconfig-group: miles # Set the group for the kubeconfig file

    - name: Install k3s
      shell: curl -sfL https://get.k3s.io | sh -

  # handlers:
  #   - name: Restart networking
  #     service:
  #       name: networking
  #       state: restarted