version: '3.8'

networks:
  default:
    driver: bridge
  vpn_network:
    driver: bridge

services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ./config/plex:/config
      - ./media:/media
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    ports:
      - "9117:9117"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config/jackett:/config
      - ./downloads:/downloads
    restart: unless-stopped
    depends_on:
      - plex

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config/radarr:/config
      - ./media:/media
      - ./downloads:/downloads
    restart: unless-stopped
    depends_on:
      - jackett

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config/sonarr:/config
      - ./media:/media
      - ./downloads:/downloads
    restart: unless-stopped
    depends_on:
      - jackett

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    ports:
      - "5055:5055"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config/overseerr:/app/config
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    networks:
      - vpn_network
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
    volumes:
      - ./config/qbittorrent:/config
      - ./downloads:/downloads
    restart: unless-stopped
    depends_on:
      - nordvpn

  nordvpn:
    image: bubuntux/nordvpn:latest
    container_name: nordvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - NORDVPN_USERNAME=${NORDVPN_USERNAME}
      - NORDVPN_PASSWORD=${NORDVPN_PASSWORD}
      - CONNECT=United_States # Change to your preferred server
      - TECHNOLOGY=NordLynx
    networks:
      - vpn_network
    restart: unless-stopped