version: '3.8'

networks:
  default:
    driver: bridge

services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ./config/plex:/config
      - ./media:/media
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    ports:
      - "9117:9117"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config/jackett:/config
      - ./downloads:/downloads
    restart: unless-stopped
    depends_on:
      - plex

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config/radarr:/config
      - ./media:/media
      - ./downloads:/downloads
    restart: unless-stopped
    depends_on:
      - jackett

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config/sonarr:/config
      - ./media:/media
      - ./downloads:/downloads
    restart: unless-stopped
    depends_on:
      - jackett

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    ports:
      - "5055:5055"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config/overseerr:/app/config
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr

  vpn:
    image: ghcr.io/bubuntux/nordvpn
    container_name: vpn
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TOKEN=${TOKEN}
      - CONNECT=${CONNECT}
      - TECHNOLOGY=${TECHNOLOGY}
      - NETWORK=10.0.0.0/24
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    dns:
      - 1.1.1.1
      - 8.8.8.8
    network_mode: bridge
    ports:
      - "8080:8080"    
    restart: unless-stopped

  torrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: service:vpn
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
    volumes:
      - ./config/qbittorrent:/config
      - ./downloads:/downloads

    depends_on:
      - vpn
    restart: unless-stopped
