services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true  
    volumes:
      - jackett_config:/config
      - jackett_downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - media

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true
    volumes:
      - sonarr_config:/config
      - sonarr_tv:/tv
      - sonarr_downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - media

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true
    volumes:
      - radarr_config:/config
      - radarr_movies:/movies
      - radarr_downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - media

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
       - PUID=1000
       - PGID=1000
       - TZ=Etc/UTC
    volumes:
       - overseerr_config:/config
    ports:
       - 5055:5055
    restart: unless-stopped
    networks:
       - overseerr

  wordpress:
    container_name: wordpress
    image: wordpress:latest
    restart: unless-stopped
    volumes:
      - ./wordpress:/app/data

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run --token "$CLOUDFLARE_TUNNEL_TOKEN"
    env_file:
      - .env
    networks:
      - overseerr

  vpn:
    image: ghcr.io/bubuntux/nordvpn
    container_name: nordvpn
    cap_add:
      - NET_ADMIN               # Required
      - NET_RAW                 # Required
    env_file:
       - .env
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - TOKEN= "$NORDVPN_TOKEN"       # Required
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - WHITELIST=showrss.info,rarbg.to,yts.mx
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
  qbittorrent:
     image: lscr.io/linuxserver/qbittorrent:latest
     container_name: qbittorrent
     depends_on:
       - vpn
     environment:
        - PUID=1000
        - PGID=1000
        - TZ=Etc/UTC
        - WEBUI_PORT=8080
     volumes:
       - qbittorrent_config:/config
       - qbittorrent_downloads:/downloads
     ports:
       - 8080:8080
       - 6881:6881
       - 6881:6881/udp
     restart: unless-stopped
    
# Make sure that you can access your server from the internet
# for example configure dmz on your router
# the torrent service would be available at https://mytorrent.duckdns.org
  # qbittorrent:
  #   image: lscr.io/linuxserver/qbittorrent:latest
  #   container_name: qbittorrent
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #     - WEBUI_PORT=8080
  #   volumes:
  #     - qbittorrent_config:/config
  #     - qbittorrent_downloads:/downloads
  #   ports:
  #     - 8080:8080
  #     - 6881:6881
  #     - 6881:6881/udp
  #   restart: unless-stopped
  #   networks:
  #     - torrent
networks:
  overseerr:
  media:
    driver: bridge

volumes:
  jackett_config:
  jackett_downloads:
  sonarr_config:
  sonarr_tv:
  sonarr_downloads:
  radarr_config:
  radarr_movies:
  radarr_downloads:
  overseerr_config:
  qbittorrent_config:
  qbittorrent_downloads:
