services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - jackett_config:/config
      - jackett_downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - media

networks:
  media:
    driver: bridge

volumes:
  jackett_config:
  jackett_downloads:
