services:
  jackett:
    # Jackett is a tool that automates the process of searching for torrents.
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000  # User ID
      - PGID=1000  # Group ID
      - TZ=Etc/UTC  # Timezone
      - AUTO_UPDATE=true  # Enable auto-update
    volumes:
      - jackett_config:/config  # Configuration files
      - jackett_downloads:/downloads  # Downloaded files
    ports:
      - 9117:9117  # Web UI port
    restart: unless-stopped
    networks:
      - media

  sonarr:
    # Sonarr is a PVR for Usenet and BitTorrent users.
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000  # User ID
      - PGID=1000  # Group ID
      - TZ=Etc/UTC  # Timezone
      - AUTO_UPDATE=true  # Enable auto-update
    volumes:
      - sonarr_config:/config  # Configuration files
      - sonarr_tv:/tv  # TV shows
      - sonarr_downloads:/downloads  # Downloaded files
    ports:
      - 8989:8989  # Web UI port
    restart: unless-stopped
    networks:
      - media

  radarr:
    # Radarr is a movie collection manager for Usenet and BitTorrent users.
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000  # User ID
      - PGID=1000  # Group ID
      - TZ=Etc/UTC  # Timezone
      - AUTO_UPDATE=true  # Enable auto-update
    volumes:
      - radarr_config:/config  # Configuration files
      - radarr_movies:/movies  # Movies
      - radarr_downloads:/downloads  # Downloaded files
    ports:
      - 7878:7878  # Web UI port
    restart: unless-stopped
    networks:
      - media

  overseerr:
    # Overseerr is a request management and media discovery tool.
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000  # User ID
      - PGID=1000  # Group ID
      - TZ=Etc/UTC  # Timezone
    volumes:
      - ../.cnf:/config  # Configuration files
    ports:
      - 5055:5055  # Web UI port
    restart: unless-stopped
    networks:
      - media

  wordpress:
    # WordPress is a free and open-source content management system.
    container_name: wordpress
    image: wordpress:latest
    restart: unless-stopped
    volumes:
      - ./wordpress:/app/data  # WordPress data

  tunnel:
    # Cloudflared Tunnel is used to securely connect to Cloudflare's network.
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run --token "$CLOUDFLARE_TUNNEL_TOKEN"
    env_file:
      - .env  # Environment variables
    networks:
      - media

  vpn:
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN               # Required
      - NET_RAW                 # Required
    env_file: 
      - .env                     # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - TOKEN="$NORDVPN_TOKEN"     # Required
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.0.0/24  # So it can be accessed within the local network
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
    ports:
      - 6881:6881  # BitTorrent port
      - 6881:6881/udp  # BitTorrent port
      - 8080:8080  # Web UI port
  qbittorrent:
    # qBittorrent is a free and open-source BitTorrent client.
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    depends_on:
      - vpn  # Depends on VPN service
    network_mode: service:vpn
    environment:
      - PUID=1000  # User ID
      - PGID=1000  # Group ID
      - TZ=Etc/UTC  # Timezone
      - WEBUI_PORT=8080  # Web UI port
    volumes:
      - qbittorrent_config:/config  # Configuration files
      - qbittorrent_downloads:/downloads  # Downloaded files
    restart: unless-stopped

  plex:
    # Plex is a media server that organizes video, music, and photos.
    image: linuxserver/plex
    container_name: plex
    env_file:
      - .env  # Environment variables
    environment:
      - PUID=1000  # User ID
      - PGID=1000  # Group ID
      - TZ=America/New_York  # Timezone
      - VERSION=docker  # Container version
    volumes:
      - ../Test:/data  # Media files
      - ../Test:/config  # Configuration files
    ports:
      - 32400:32400  # Plex port
      - 3005:3005  # Plex port
      - 8324:8324  # Plex port
      - 32469:32469  # Plex port
      - 1900:1900  # Plex port
      - 32410:32410  # Plex port
      - 32412:32412  # Plex port
      - 32413:32413  # Plex port
      - 32414:32414  # Plex port
    networks:
      - media  # Plex network

networks:
  media:

volumes:
  jackett_config:
  jackett_downloads:
  sonarr_config:
  sonarr_tv:
  sonarr_downloads:
  radarr_config:
  radarr_movies:
  radarr_downloads:
  qbittorrent_config:
  qbittorrent_downloads:
